# Generated by Django 6.0.6 on 2026-06-13 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('expense_added', 'Expense Added'), ('settlement_request', 'Settlement Request'), ('settlement_completed', 'Settlement Completed'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('import_completed', 'Import Completed'), ('import_failed', 'Import Failed'), ('group_invitation', 'Group Invitation'), ('system', 'System Notification')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
