# Generated by Django 6.0.6 on 2026-06-13 13:41

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ British Pound'), ('JPY', '¥ Japanese Yen')], default='INR', max_length=3)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('travel', 'Travel'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=30)),
                ('date', models.DateField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('exact', 'Exact Amount'), ('percent', 'Percentage'), ('shares', 'Shares'), ('settlement', 'Settlement Payment')], default='equal', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expense_attachments/')),
                ('is_settlement', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('share_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('shares', models.PositiveIntegerField(default=1)),
                ('is_settled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'expense_participants',
            },
        ),
    ]
