# Generated by Django 6.0.6 on 2026-06-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseparticipant',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='expenseparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'date'], name='expenses_group_i_9168aa_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by', 'date'], name='expenses_paid_by_27d0de_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'is_deleted'], name='expenses_group_i_14ca95_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseparticipant',
            index=models.Index(fields=['expense', 'user'], name='expense_par_expense_64e90d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseparticipant',
            unique_together={('expense', 'user')},
        ),
    ]
