# Generated by Django 6.0.6 on 2026-06-13 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('row_number_b', models.IntegerField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('duplicate', 'Duplicate Expense'), ('near_duplicate', 'Near Duplicate'), ('missing_field', 'Missing Required Field'), ('negative_amount', 'Negative Amount'), ('refund', 'Possible Refund'), ('settlement_as_expense', 'Settlement as Expense'), ('unknown_member', 'Unknown Member'), ('future_date', 'Future Date'), ('invalid_currency', 'Invalid Currency'), ('invalid_split', 'Invalid Split Values'), ('outside_membership', 'Outside Membership Period'), ('same_event', 'Possible Same Event'), ('malformed_row', 'Malformed Row'), ('incorrect_total', 'Incorrect Total'), ('missing_participants', 'Missing Participants')], max_length=30)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField()),
                ('row_data', models.JSONField(blank=True, null=True)),
                ('row_data_b', models.JSONField(blank=True, null=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('user_decision', models.CharField(blank=True, choices=[('keep_first', 'Keep First'), ('keep_second', 'Keep Second'), ('merge', 'Merge'), ('ignore', 'Ignore Both'), ('mark_separate', 'Mark as Separate'), ('accept', 'Accept'), ('skip', 'Skip Row')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_anomalies',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('validating', 'Validating'), ('review', 'Awaiting Review'), ('approved', 'Approved'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=12)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='groups.group')),
            ],
            options={
                'db_table': 'import_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
