# Generated by Django 6.0.6 on 2026-06-13 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlement',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['group', 'status'], name='settlements_group_i_8b73c3_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payer', 'receiver'], name='settlements_payer_i_ddd3c6_idx'),
        ),
    ]
